### ISSUE TITLE
possible bug in "protected by fire" logic

### ISSUE THREAD

**Issue by barrybecker4** [krajzeg/compact-conflict#3]
I think I found another one.
I believe that 
`var invincibility = upgradeLevel(state, fromOwner, FIRE);`
should be 
`var invincibility = upgradeLevel(state, toOwner, FIRE);`

because the invincibility value is for the guy being attacked.
If invincibility >0 and they lose the roll, then it says "Protected by fire!".

**Comment by krajzeg** [comment]
Nope, this one is correct. Invincibility protects the attacker (the one who moved an army, so `fromOwner`) and this is implemented correctly below.

https://github.com/krajzeg/compact-conflict/blob/772f4a0309c2a41b3360d0dd48b5e235fbb98658/erisk.js#L1790-L1797
